-- 게시판 디자인 설정 (구성 요소, 리스트 항목, 리스트 옵션, 텍스트, 배경/테두리)
ALTER TABLE public.boards
  -- 구성 요소
  ADD COLUMN IF NOT EXISTS show_board_name BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_total_count BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_profile_image BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_search BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS image_lightbox BOOLEAN NOT NULL DEFAULT true,
  -- 리스트 항목 (글쓴이/조회수는 기존 컬럼)
  ADD COLUMN IF NOT EXISTS show_created_time BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_content_preview BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_category BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_comment_count BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_like_count BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_share BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_print BOOLEAN NOT NULL DEFAULT false,
  -- 리스트 옵션
  ADD COLUMN IF NOT EXISTS image_ratio TEXT NOT NULL DEFAULT '4:3',
  ADD COLUMN IF NOT EXISTS cols_desktop INT NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS gap_px INT NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS visible_rows INT NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS cols_mobile INT NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS keep_cols_on_expand BOOLEAN NOT NULL DEFAULT true,
  -- 텍스트
  ADD COLUMN IF NOT EXISTS title_font_size INT NOT NULL DEFAULT 14,
  ADD COLUMN IF NOT EXISTS content_font_size INT NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS padding_px INT NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS content_preview_lines INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS text_align TEXT NOT NULL DEFAULT 'left',
  -- 배경/테두리
  ADD COLUMN IF NOT EXISTS border_radius INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS border_width INT NOT NULL DEFAULT 1;
